name: Java release with Maven

on:
  push:
    branches: [ main ]

jobs:
  release:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build with Maven Wrapper
        run: >-
          ./mvnw -B spring-boot:build-image
          -Ddocker.publishRegistry.username=${{ github.actor }}
          -Ddocker.publishRegistry.password=${{ secrets.GITHUB_TOKEN }}
          -Ddocker.publishRegistry.url=ghcr.io
          -Dspring-boot.build-image.publish=true
          -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:latest
          -Dorg.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
